### ISSUE TITLE
My films section

### ISSUE THREAD

**Issue by strachsel** [araedavis/screen#17]
As a user I can create a custom schedule of films I want to see, and access this schedule via the browser, on mobile (on or offline), or a print-friendly version because film festivals are complicated and advanced planning is necessary.  

Create online itinerary section where user can save the movies

**Comment by araedavis** [comment]
- [x] add favorite button/star/heart feature to main films page
- [x] when a film is favorited, it appears in the My Films view
- [x] user can edit My Films to remove films from My Films view
- [x] cache My Films in local storage so user can return to the app and see their schedule.
